#### This is the list of solutions to problems 121 - 130 in the MATH 1MP3 Problem Set.

***
Import(s):

In [2]:
# Import(s):
import numpy as np

***
(121) Given a matrix A, predict what the print statements output.

In [38]:
# Variable(s):
A = np.arange(1, 17).reshape(4, 4)
print(A)

# Output:
print(A[2, 3])  # 12
print(A[:, 0])  # [1 5 9 13]
print(A[2:4, 1:2])  # [[10] [14]]
print(A[0, 0])  # 1
print(A[:, 0:2])  # [[1 2] [5 6] [9 10] [13 14]]
print(A[::2,])  # [[1 2 3 4] [9 10 11 12]]
print(A[2:,])  # [[9 10 11 12] [13 14 15 16]]
print(A[2:4, 0:2])  # [[9 10] [13 14]]
print(A[0:2, ::3])  # [[1 4] [5 8]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
12
[ 1  5  9 13]
[[10]
 [14]]
1
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 9 10]
 [13 14]]
[[1 4]
 [5 8]]


***
(122) Make functions that takes in a square NumPy array as a parameter and performs the following actions using slicing:
1: Extract the i-th row of A
2: Extract the j-th column of B
3: Assume that the NumPy array is 3x3. Extract C00
4: Assume that the NumPy array is 3x3. Extract C01
5: Assume that the NumPy array is 3x3. Extract C02

In [45]:
# Function(s):
def row_extractor(M, i):
    # Output:
    return M[i - 1]

def col_extractor(M, j):
    # Output:
    return M[:, j - 1]

def cofactor_1(M):
    # Output:
    return M[1:, 1:]

def cofactor_2(M):
    # Output:
    return M[1:, ::2]

def cofactor_3(M):
    # Output:
    return M[1:, :2]

***
(123) Make a function that takes in two natural numbers i and j, and a NumPy array and returns the i-th row and j-th column from the NumPy array.

In [40]:
# Function(s):
def row_col_extractor(i, j, M):
    # Output:
    return M[i - 1], M[:, j - 1]

***
(124) Make a function that takes in a 3x3 matrix as a NumPy array and returns its determinant using cofactor expansion.

In [46]:
# Function(s):
def det_2x2(M):
    # Output:
    return M[0, 0] * M[1, 1] - M[0, 1] * M[1, 0]

def det_3x3(M):
    # Variable(s):
    det_array = np.array([det_2x2(cofactor_1(M)), - det_2x2(cofactor_2(M)), det_2x2(cofactor_3(M))])

    # Output:
    return np.dot(M[0], det_array)

***
(125) Make a function that takes in a 4x4 matrix as a NumPy array and returns its determinant using cofactor expansion.

In [49]:
# Function(s):
def det_4x4(M):
    # Variable(s):
    cofact_1 = M[1:, 1:]
    cofact_2 = np.concatenate((M[1:, 0].reshape(3, 1), M[1:, 2:]), axis=1)
    cofact_3 = np.concatenate((M[1:, 0:2], M[1:, 3].reshape(3, 1)), axis=1)
    cofact_4 = M[1:, :3]

    # Calculations:
    det_array = np.array([det_3x3(cofact_1), - det_3x3(cofact_2), det_3x3(cofact_3), - det_3x3(cofact_4)])

    # Output:
    return np.dot(M[0], det_array)

***
(126) Make a function that returns a NumPy array of the values of g(x) = e^(0.2x) of numbers ∈ [0, 4] such that each number is 0.001 greater than the previous.

In [43]:
# Function(s):
def g_array():
    # Output:
    return np.exp(- 0.2 * np.append(np.arange(0, 4, 0.001), 4))

# Output:
g_array()

array([1.        , 0.99980002, 0.99960008, ..., 0.44950873, 0.44941884,
       0.44932896])

***
(127) Make a function that returns a NumPy array of the values of f(x) = sin(2x) - 3 cos(x / 5) at 150 equally spaced values between 0 and π / 2.

In [44]:
# Function(s):
def f(x):
    # Output:
    return np.sin(2 * x) - 3 * np.cos(x / 5)

def f_array():
    # Output:
    return f(np.linspace(0, np.pi / 2, 152))

# Output:
f_array()

array([-3.        , -2.97918976, -2.95837554, -2.93756633, -2.91677114,
       -2.89599895, -2.87525872, -2.85455939, -2.8339099 , -2.81331913,
       -2.79279595, -2.7723492 , -2.75198766, -2.73172009, -2.71155518,
       -2.69150159, -2.67156792, -2.65176272, -2.63209445, -2.61257155,
       -2.59320235, -2.57399513, -2.55495809, -2.53609935, -2.51742695,
       -2.49894885, -2.48067289, -2.46260685, -2.44475841, -2.42713514,
       -2.4097445 , -2.39259385, -2.37569046, -2.35904147, -2.34265389,
       -2.32653464, -2.31069051, -2.29512814, -2.27985409, -2.26487474,
       -2.25019637, -2.23582511, -2.22176696, -2.20802777, -2.19461325,
       -2.18152897, -2.16878035, -2.15637264, -2.14431097, -2.13260028,
       -2.12124538, -2.11025091, -2.09962134, -2.08936099, -2.07947402,
       -2.06996439, -2.06083594, -2.05209229, -2.04373692, -2.03577313,
       -2.02820404, -2.0210326 , -2.01426157, -2.00789354, -2.00193093,
       -1.99637596, -1.99123067, -1.98649694, -1.98217645, -1.97

***
(128) Make a function that returns a NumPy array of the values of sin(x) of numbers ∈ [0, 2π] such that each number is π / 250 greater than the previous.

In [45]:
# Function(s):
def sin_array():
    # Output:
    return np.sin(np.arange(0, 2.004 * np.pi, np.pi / 250))

# Output:
sin_array()

array([ 0.00000000e+00,  1.25660399e-02,  2.51300954e-02,  3.76901827e-02,
        5.02443182e-02,  6.27905195e-02,  7.53268055e-02,  8.78511966e-02,
        1.00361715e-01,  1.12856385e-01,  1.25333234e-01,  1.37790291e-01,
        1.50225589e-01,  1.62637165e-01,  1.75023059e-01,  1.87381315e-01,
        1.99709981e-01,  2.12007110e-01,  2.24270761e-01,  2.36498997e-01,
        2.48689887e-01,  2.60841506e-01,  2.72951936e-01,  2.85019262e-01,
        2.97041582e-01,  3.09016994e-01,  3.20943610e-01,  3.32819545e-01,
        3.44642923e-01,  3.56411879e-01,  3.68124553e-01,  3.79779096e-01,
        3.91373667e-01,  4.02906436e-01,  4.14375581e-01,  4.25779292e-01,
        4.37115767e-01,  4.48383216e-01,  4.59579861e-01,  4.70703932e-01,
        4.81753674e-01,  4.92727342e-01,  5.03623202e-01,  5.14439534e-01,
        5.25174630e-01,  5.35826795e-01,  5.46394347e-01,  5.56875616e-01,
        5.67268949e-01,  5.77572703e-01,  5.87785252e-01,  5.97904983e-01,
        6.07930298e-01,  

***
(129) Make a function that returns the mean of the squares of the first 100 natural numbers.

In [46]:
# Function(s):
def hundred_squares_mean():
    # Output:
    return np.mean(pow(np.arange(1, 101), 2))

# Output:
hundred_squares_mean()

3383.5

***
(130) Make a function that returns the sum of sin(1 / x), ∀x ∈ [1, 105] ∋ x is odd.

In [47]:
# Function(s):
def sin_sum():
    # Output:
    return np.sum(np.sin(1 / np.arange(1, 107, 2)))

# Output:
sin_sum()

2.7997873849759447