#### This is the list of solutions to problems 141 - 146 in the MATH 1MP3 Problem Set.

***
Import(s):

In [1]:
# Import(s):
import numpy as np

***
(141) Given two NumPy arrays A and B, predict what each print statement outputs.

In [2]:
# Variable(s):
A = np.arange(1, 11)  # [1 2 3 4 5 6 7 8 9 10]
B = np.arange(-6, 13, 2)  # [-6 -4 -2 0 2 4 6 8 10 12]

# Output:
A[A > 4] = 55
print(A)  # [1 2 3 4 55 55 55 55 55 55]

A = np.arange(1, 11)
A[B > 4] = 55
print(A)  # [1 2 3 4 5 6 55 55 55 55]

A = np.arange(1, 11)
A[A == B] = 333
print(A)  # [1 2 3 4 5 6 7 333 9 10]

A = np.arange(1, 11)
A[np.abs(A - B) <= 2] = 17
print(A)  # [1 2 3 4 5 17 17 17 17 17]

[ 1  2  3  4 55 55 55 55 55 55]
[ 1  2  3  4  5  6 55 55 55 55]
[  1   2   3   4   5   6   7 333   9  10]
[ 1  2  3  4  5 17 17 17 17 17]


***
(142) Given a NumPy arrays M, predict what each print statement outputs.

In [3]:
# Variable(s):
M = np.arange(-5, 7).reshape(3, 4)  # [[-5 -4 -3 -2] [-1 0 1 2] [3 4 5 6]]

# Output:
print(M <= 2)  # [[True True True True] [True True True True] [False False False False]]
print(pow(M, 2) <= 4)  # [[False False False True] [True True True True] [False False False False]]
print(np.logical_or(-2 < M, M > 2))  # [[False False False False] [True True True True] [True True True True]]
print(np.logical_not(M > 2))  # [[True True True True] [True True True True] [False False False False]]

[[ True  True  True  True]
 [ True  True  True  True]
 [False False False False]]
[[False False False  True]
 [ True  True  True  True]
 [False False False False]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[[ True  True  True  True]
 [ True  True  True  True]
 [False False False False]]


***
(143) Given a NumPy array M, predict what each print statement outputs.

In [4]:
# Variable(s):
M = np.arange(-5, 7).reshape(3, 4)  # [[-5 -4 -3 -2] [-1 0 1 2] [3 4 5 6]]

# Output:
print(M[M > 4])  # [5 6]
print(M[M == 4])  # [4]
print(M[2 * M - 5 > 0])  # [3 4 5 6]
print(M[np.exp(M) > 1])  # [1 2 3 4 5 6]

[5 6]
[4]
[3 4 5 6]
[1 2 3 4 5 6]


***
(144) Given a NumPy array M, predict what each print statement outputs.

In [5]:
# Variable(s):
M = np.arange(-5, 7).reshape(3, 4)  # [[-5 -4 -3 -2] [-1 0 1 2] [3 4 5 6]]

# Output:
M[M > 0] = 1
print(M)  # [[-5 -4 -3 -2] [-1 0 1 1] [1 1 1 1]]

M = np.arange(-5, 7).reshape(3, 4)
M[M >= 0] = -6
print(M)  # [[-5 -4 -3 -2] [-1 -6 -6 -6] [-6 -6 -6 -6]]

M = np.arange(-5, 7).reshape(3, 4)
M[M == 0] = 100
print(M)  # [[-5 -4 -3 -2] [-1 100 1 2] [3 4 5 6]]

M = np.arange(-5, 7).reshape(3, 4)
M[M % 2 == 0] = 77
print(M)  # [[-5 77 -3 77] [-1 77 1 77] [3 77 5 77]]

[[-5 -4 -3 -2]
 [-1  0  1  1]
 [ 1  1  1  1]]
[[-5 -4 -3 -2]
 [-1 -6 -6 -6]
 [-6 -6 -6 -6]]
[[ -5  -4  -3  -2]
 [ -1 100   1   2]
 [  3   4   5   6]]
[[-5 77 -3 77]
 [-1 77  1 77]
 [ 3 77  5 77]]


***
(145) Make functions that take in a non-zero 2D matrix M of type float and returns a logical NumPy array L whose entry is True if:
1: M[i, j] >= 0.
2: M[i, j] >= np.mean(M).
3: M[i, j] == np.amax(M, axis=1).

In [6]:
# Function(s):
def logical_positive(M):
    # Output:
    return M >= 0

def logical_above_mean(M):
    # Output:
    return M >= np.mean(M)

def logical_max_row(M):
    # Output:
    return M == np.amax(M, axis=1)

***
(146) Make functions that take in a non-zero 2D matrix M of type float and:
1: Returns M[M > 4].
2: Returns M[M > np.mean(M)].
3: Replaces all entries greater than 5 with 0.
4: Replaces all entries greater than the mean with the mean.

In [7]:
# Function(s):
def above_4(M):
    # Output:
    return M[M > 4]

def above_mean(M):
    # Output:
    return M[M > np.mean(M)]

def replace_5(M):
    # Logic:
    M[M == 5] = 0

    # Output:
    return M

def replace_above_mean(M):
    # Variable(s):
    mean = np.mean(M)

    # Logic:
    M[M > mean] = mean

    # Output:
    return M